### ISSUE TITLE
duplicate key for object get first value

### ISSUE THREAD

**Issue by dlintw** [go-akka/configuration#12]
sample.conf
```
server {
  addr: 239.0.0.1
  addr: 224.0.0.0
}
```
expect get server.addr is 224.0.0.0 but got 239.0.0.1

**Comment by artemkaxboy** [comment]
I tried to reproduce the behavior with file and LoadConfig and with ParseString, but it gave me the last value as it supposed to.
```go
conf1 := LoadConfig("tests/sample.conf")
val1 := conf1.GetString("server.addr", "")
log.Println(val1) // 2020/01/09 22:39:27 224.0.0.0

conf2 := ParseString(`server {addr: 239.0.0.1,addr: 224.0.0.0}`)
val2 := conf2.GetString("server.addr", "")
log.Println(val2) // 2020/01/09 22:39:27 224.0.0.0
```
Both examples give "224.0.0.0".

Can you give an example to reproduce the issue.

**Comment by dlintw** [comment]
Sorry, I can't not reproduce it. too.
