### ISSUE TITLE
Missing value when optional substitution is unresolved

### ISSUE THREAD

**Issue by bogatuadrian** [go-akka/configuration#5]
### Expected

When trying to overwrite a variable with an optional substitution, if the substitution cannot be resolved the last value of the variable should be kept.

### Got

The variable's value is overwritten by the empty string.

### Example

With the `DATABASE_URL` environment variable not being set:

```go
package main

import (
	"fmt"

	"github.com/go-akka/configuration"
)

var cfg = `
url = "root:@tcp(127.0.0.1:3306)/table?parseTime=True&loc=Local"
url = ${?DATABASE_URL}
`

func main() {
	conf := configuration.ParseString(cfg)
	fmt.Println("url =", conf.GetString("url"))
	// Output: url = 
	// Expected: url = root:@tcp(127.0.0.1:3306)/table?parseTime=True&loc=Local
}
```

I tried to inspect the code and I think the problem appears because `GetOrCreateKey()` (https://github.com/go-akka/configuration/blob/master/hocon/parser.go#L90) moves the values into the `oldValue` variable which is never used when handling optional substitution.

I would be happy to start a PR if someone could point me in the right direction :)

**Comment by xujinzheng** [comment]
I will try to fix this issue.

**Comment by thisperfect** [comment]
this issue  still exist

**Comment by xujinzheng** [comment]
I will fix this issue while I have free time.

**Comment by btnguyen2k** [comment]
Hi @xujinzheng 

I created a PR (https://github.com/go-akka/configuration/pull/6) to fix this issue.
Please review and accept.

Best regards,
Thanh Nguyen
